version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: document-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: documents
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # app:
  #   build: .
  #   ports:
  #     - "9400:9400"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres

volumes:
  pgdata:
